name: brainyquotebot

on:
  schedule:
    - cron: '36 * * * *'  # once every two hours
    
jobs:
  brainyquotebot-tweet:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: run_bot
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: git config
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
      - name: Create and post tweet
        run: Rscript R/brainyquotebot-tweet.R
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          
